global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "iaair_alerts.yml"

scrape_configs:
  - job_name: 'iaair-api'
    static_configs:
      - targets: ['172.17.0.1:8000']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093